export const cards = [
  {
    image: "./images/pancakes.jpg",
    alt: "Fluffy American pancakes",
    title: "Fluffy American pancakes",
    cookingTime: "40min",
    category: "Dessert",
    shortDescription:
      "You'll flip over these next level fluffy American pancakes – the perfect indulgent brunch treat. Serve with our tangy cherry syrup and irresistible maple syrup and bacon.",
    ingredients: [
      "200g self-raising flour",
      "1 ½ tsp baking powder",
      "1 tbsp golden caster sugar",
      "3 large eggs",
      "25g melted butter, plus extra for cooking",
      "200ml milk",
      "vegetable oil, for cooking",
    ],
    method: [
      "STEP 1 Mix 200g self-raising flour, 1 ½ tsp baking powder, 1 tbsp golden caster sugar and a pinch of salt together in a large bowl.",
      "STEP 2 Create a well in the centre with the back of your spoon then add 3 large eggs, 25g melted butter and 200ml milk.",
      "STEP 3 Whisk together either with a balloon whisk or electric hand beaters until smooth then pour into a jug.",
      "STEP 4 Heat a small knob of butter and 1 tsp of oil in a large, non-stick frying pan over a medium heat. When the butter looks frothy, pour in rounds of the batter, approximately 8cm wide. Make sure you don’t put the pancakes too close together as they will spread during cooking. Cook the pancakes on one side for about 1-2 mins or until lots of tiny bubbles start to appear and pop on the surface. Flip the pancakes over and cook for a further minute on the other side. Repeat until all the batter is used up.",
      "STEP 5 Serve your pancakes stacked up on a plate with a drizzle of maple syrup and any of your favourite toppings.",
    ],
  },
  {
    image: "./images/crumpets.jpg",
    alt: "Homemade crumpets with ricotta",
    title: "Homemade crumpets with ricotta",
    cookingTime: "40min",
    category: "Dessert",
    shortDescription:
      "Forget shop-bought crumpets, here's how to do them at home this weekend. Delicious served with a light topping of summer fruits, fresh ricotta and honey.",
    ingredients: [
      "260ml milk",
      "1 tsp caster sugar",
      "7g sachet fast-action dried yeast",
      "220g plain flour",
      "½ tsp bicarbonate of soda",
      "vegetable oil, for oiling and cooking",
    ],
    method: [
      "STEP 1 In a medium saucepan, heat the milk and 60ml water until warm but not hot. Take off the heat, add the sugar and yeast and stir in, then set aside for 15 mins.",
      "STEP 2 Sift the flour, bicarb and a large pinch of salt into a mixing bowl. Make a well in the middle and add the milk mixture. Stir to make a batter, then cover with a tea towel and leave for 40-50 mins until frothy.",
      "STEP 3 When ready to cook, heat a flat, non-stick frying pan over a medium-high heat and oil four cooking rings, roughly 8cm diameter. Add a splash of cooking oil to each ring and tip in a ladleful of the batter (you want them between half and three-quarters full). Cook over a low heat for 15 mins or until bubbles form at the top and pop.",
      "STEP 4 Gently lift off the ring, running a knife around the edge if it’s stuck. Flip the crumpets over to cook the top for a minute or so, then take out of the pan and leave to cool on a wire rack while you cook a second batch.",
      "STEP 5 When ready to serve, toast the crumpets lightly. Spoon over the ricotta, scatter over the berries and finish with a drizzle of honey.",
    ],
  },
  {
    image: "./images/salmon.jpg",
    alt: "Teriyaki salmon",
    title: "Teriyaki salmon",
    cookingTime: "20min",
    category: "Lunch",
    shortDescription:
      "Sweet chilli, honey, sesame oil, mirin and soy combine to make a punchy sauce for this teriyaki salmon. Serve with sesame pak choi for a quick midweek meal",
    ingredients: [
      "2 skinless salmon fillets",
      "1 tbsp sweet chilli sauce",
      "1 tbsp honey",
      "1 tsp sesame oil",
      "1 tbsp mirin or dry sherry",
      "2 tbsp soy sauce",
      "2 tsp finely grated ginger",
      "brown rice or noodles, to serve (optional)",
    ],

    method: [
      "STEP 1 Heat oven to 200C/180C fan/gas 6 and put the skinless salmon fillets in a shallow baking dish.",
      "STEP 2 Mix the sweet chilli sauce, honey, sesame oil, mirin or dry sherry, soy sauce and finely grated ginger in a small bowl and pour over the salmon so the fillets are completely covered. Bake for 10 mins.",
      "STEP 3 Meanwhile, cut a slice across the base of the pak choi so the leaves separate.",
      "STEP 4 Heat the vegetable oil and sesame oil in a wok, add the grated garlic cloves and stir-fry briefly to soften.",
      "STEP 5 Add the pak choi and fry until the leaves start to wilt. Pour over the vegetable stock, tightly cover the pan and allow to cook for 5 mins – you're aiming for the stems to be tender but still have a bit of bite.",
      "STEP 6 Serve the pak choi in shallow bowls, top with the salmon and spoon over the juices. Scatter with the toasted sesame seeds and serve with brown rice or noodles, if you like.",
    ],
  },
  {
    image: "./images/wraps.jpg",
    alt: "Spicy chicken & avocado wraps",
    title: "Spicy chicken & avocado wraps",
    cookingTime: "13min",
    category: "Lunch",
    shortDescription:
      "Pan-fry lean chicken breast with lime, chilli and garlic, then pile onto seeded tortilla wraps. Cool before assembling if packing for lunch",
    ingredients: [
      "1 chicken breast (approx 180g), thinly sliced at an angle",
      "generous squeeze juice of 0.5 lime",
      "½ tsp mild chilli powder",
      "1 garlic clove, chopped",
      "1 tsp olive oil",
      "2 seeded wraps",
      "1 avocado, halved and stoned",
      "1 roasted red pepper from a jar, sliced",
      "a few sprigs coriander, chopped",
    ],

    method: [
      "STEP 1 Mix the chicken with the lime juice, chilli powder and garlic.",
      "STEP 2 Heat the oil in a non-stick frying pan then fry the chicken for a couple of mins – it will cook very quickly so keep an eye on it. Meanwhile, warm the wraps following the pack instructions or, if you have a gas hob, heat them over the flame to slightly char them. Do not let them dry out or they are difficult to roll.",
      "STEP 3 Squash half an avocado onto each wrap, add the peppers to the pan to warm them through then pile onto the wraps with the chicken, and sprinkle over the coriander. Roll up, cut in half and eat with your fingers.",
    ],
  },
  {
    image: "./images/oats.jpg",
    alt: "Overnight oats",
    title: "Overnight oats",
    cookingTime: "10min",
    category: "Breakfast",
    shortDescription:
      "Adapt this recipe for easy overnight oats to suit your tastes. You can add dried fruit, seeds and nuts, grated apple or pear or chopped tropical fruits for the perfect healthy breakfast",
    ingredients: [
      "¼ tsp ground cinnamon",
      "50g rolled porridge oats",
      "2 tbsp natural yogurt",
      "50g mixed berries",
      "drizzle of honey",
      "½ tbsp nut butter (we used almond)",
    ],

    method: [
      "STEP 1 The night before serving, stir the cinnamon and 100ml water (or milk) into your oats with a pinch of salt.",
      "STEP 2 The next day, loosen with a little more water (or milk) if needed. Top with the yogurt, berries, a drizzle of honey and the nut butter.",
    ],
  },
  {
    image: "./images/omelette.jpg",
    alt: "Cheese omelette",
    title: "Cheese omelette",
    cookingTime: "10min",
    category: "Breakfast",
    shortDescription:
      "Rustle up a simple omelette for a quick and easy snack any time of day. Use mature cheddar for maximum cheesy flavour",
    ingredients: [
      "2 eggs",
      "½ tbsp olive oil",
      "1 tbsp butter",
      "15g mature cheddar, finely grated",
    ],
    method: [
      "STEP 1 Crack the eggs into a jug and whisk well with a fork. Season with a pinch of salt.",
      "STEP 2 Heat the oil and butter in a medium non-stick frying pan over a medium-low heat. Once the butter has started to foam, pour in the eggs and tilt to cover the base of the pan. Using a spatula, gently draw in the eggs from four points so there are folds in the centre. Do this once or twice, then leave the eggs to cook gently for 2-3 mins, until there's a little raw egg still in the middle. Sprinkle over the cheese and, using your spatula, gently fold the omelette in half. Switch off the heat and let the residual heat from the pan melt the cheese for 1 min. Slide onto your plate and sprinkle over some black pepper to serve.",
    ],
  },
  {
    image: "./images/pasta-chicken.jpg",
    alt: "Chicken & bacon pasta",
    title: "Chicken & bacon pasta",
    cookingTime: "40min",
    category: "Dinner",
    shortDescription:
      "Toss chicken and bacon with ribbons of tagliatelle in a deliciously creamy sauce to make this easy pasta dish. Serve with a green salad for an easy supper",
    ingredients: [
      "2 tbsp olive oil",
      "1 tbsp butter",
      "1 onion, finely chopped",
      "1 large garlic clove, finely grated",
      "200ml double cream",
      "100g mascarpone",
      "75g parmesan, finely grated",
      "1 chicken stock cube",
      "2 cooked chicken breasts (about 210g), shredded",
      "8 rashers cooked streaky bacon (about 25g), roughly chopped",
      "300g tagliatelle",
      "¼ small bunch of parsley, finely chopped",
      "green salad, to serve",
    ],
    method: [
      "STEP 1 Heat the oil and butter in a medium saucepan over a low heat and fry the onion for 10 mins, or until softened and translucent. Add the garlic and cook for 2 mins more. Add the cream, mascarpone, parmesan and stock cube. Give it a stir and add the cooked chicken and bacon to heat through.",
      "STEP 2 Meanwhile, cook the pasta following pack instructions. Reserve 100ml of the pasta water. Toss the pasta in the creamy sauce and enough of the reserved water to loosen. Season with black pepper. Top with the parsley and serve with a green salad.",
    ],
  },
  {
    image: "./images/cheese-scone.jpg",
    alt: "Classic cheese scones",
    title: "Classic cheese scones",
    cookingTime: "35min",
    category: "Snack",
    shortDescription:
      "Indulge in some cheese scones for afternoon tea or as part of a picnic. They're also great served alongside soups and you can freeze them for later use",
    ingredients: [
      "225g self-raising flour, plus extra for dusting",
      "pinch of salt",
      "pinch of cayenne pepper",
      "1 tsp baking powder",
      "55g chilled butter, cut into cubes",
      "120g mature cheddar, grated",
      "90-100ml milk, plus 1 tbsp for glazing",
    ],
    method: [
      "STEP 1 Heat the oven to 200C/180C fan/gas 6 with a large baking tray inside. Sift the flour, salt, cayenne pepper and baking powder into a bowl, then sift again to make sure the ingredients are thoroughly combined.",
      "STEP 2 Add the butter to the bowl and combine with your fingertips to make breadcrumbs. Sprinkle 100g of the cheese into the breadcrumb mixture and rub together until evenly distributed. Try not to mix too much as the heat from your hands may start to melt the butter.",
      "STEP 3 Make a well in the centre of the mixture and pour in enough milk to give a fairly soft but firm dough. Do not pour in all the milk at once as you may not need it all to get the right consistency.",
      "STEP 4 Lightly flour a surface and roll out the dough to approximately 2cm thick. Cut out the scones with a medium (about 8cm) cutter, then put on a sheet of baking parchment, glaze with a little milk and sprinkle with the remaining cheese. Slide onto the hot oven tray.",
      "STEP 5 Bake in the oven for 15-20 mins or until golden brown and cooked through.",
    ],
  },
];
